name: Build and deploy vision-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    #   - name: Log in to Docker Hub
    #     run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_be210335c5564249ada5842821b7667b }}
          password: ${{ secrets.AzureAppService_ContainerPassword_128ecd5bb5e14760a7f332d6601dbdb8 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_be210335c5564249ada5842821b7667b }}/toberi/vision-server:${{ github.sha }}
          file: ./Dockerfile
#       - name: Set up .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: "8.x"
#           include-prerelease: true

#       - name: Build with dotnet
#         run: dotnet build --configuration Release

#       - name: dotnet publish
#         run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v3
#         with:
#           name: .net-app
#           path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'vision-backend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_47a8a8b9c1574711b55badb91c89f91c }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_be210335c5564249ada5842821b7667b }}/toberi/vision-server:${{ github.sha }}'
